from flask import Flask, jsonify
from flask_cors import CORS
import json
import os
from datetime import datetime

# -------------------------------
# Path Resolution (OS Safe)
# -------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "pattern_finder", "outputs")

TOPOLOGY_PATH = os.path.join(OUTPUT_DIR, "topology.json")
TRAFFIC_PATH = os.path.join(OUTPUT_DIR, "traffic.json")  # Optional / future use

# -------------------------------
# Flask App
# -------------------------------
app = Flask(__name__)
CORS(app)

# -------------------------------
# Health Check
# -------------------------------
@app.route("/api/health", methods=["GET"])
def health_check():
    return jsonify({
        "status": "ok",
        "service": "Nokia Fronthaul API",
        "timestamp": datetime.utcnow().isoformat() + "Z"
    })


# -------------------------------
# Topology Endpoint
# -------------------------------
@app.route("/api/topology", methods=["GET"])
def get_topology():
    if not os.path.exists(TOPOLOGY_PATH):
        return jsonify({
            "error": "Topology not generated yet",
            "hint": "Run pattern_finder/main.py to generate topology.json"
        }), 404

    with open(TOPOLOGY_PATH, "r") as f:
        data = json.load(f)

    return jsonify(data)


# -------------------------------
# Traffic Endpoint (Future-Ready)
# -------------------------------
@app.route("/api/traffic", methods=["GET"])
def get_traffic():
    """
    Returns time-series traffic / loss data for heatmap
    This can be generated by pattern_finder later
    """
    if not os.path.exists(TRAFFIC_PATH):
        return jsonify({
            "warning": "Traffic data not available yet",
            "traffic": []
        }), 200

    with open(TRAFFIC_PATH, "r") as f:
        data = json.load(f)

    return jsonify(data)


# -------------------------------
# Run Server
# -------------------------------
if __name__ == "__main__":
    print("🚀 Nokia Fronthaul Backend API")
    print("📡 Health:   http://localhost:5000/api/health")
    print("🧠 Topology: http://localhost:5000/api/topology")
    print("📈 Traffic:  http://localhost:5000/api/traffic\n")

    app.run(host="0.0.0.0", port=5000, debug=True)
